### ISSUE TITLE
report an err

### ISSUE THREAD

**Issue by surqing** [CcQunResearch/RAGCL#2]
When I execute python central.py followed by python main(sup).py, I get the following error. What should I do?
```
(lmsps_d) xmz3@bigdata1:~/wsq/RAGCL$ python3 centrality.py 
(lmsps_d) xmz3@bigdata1:~/wsq/RAGCL$ python3 Main/main\(sup\).py 
[nltk_data] Downloading package punkt to /media/xmz3/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt to /media/xmz3/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Traceback (most recent call last):
  File "RAGCL/Main/main(sup).py", line 176, in <module>
    sentences = collect_sentences(label_source_path, unlabel_dataset_path, unsup_train_size, lang, tokenize_mode)
  File "RAGCL/Main/word2vec.py", line 74, in collect_sentences
    sentences = collect_label_sentences(label_source_path) + collect_unlabel_sentences(unlabel_path, unsup_train_size)
  File "RAGCL/Main/word2vec.py", line 82, in collect_label_sentences
    for filename in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'RAGCL/Main/../Data/Weibo/source'
```

**Comment by surqing** [comment]
Hello, could you please provide me with the datasets for the experiment in your paper?

**Comment by CcQunResearch** [comment]
We will be uploading the data set we used this week (before May 20). The link will be placed in README.md.
